# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/PIS_1/PIS_1.srcs/sources_1/ip/ram_10_19_62/ram_10_19_62.xci
# IP: The module: 'ram_10_19_62' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/PIS_1/PIS_1.gen/sources_1/ip/ram_10_19_62/ram_10_19_62_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_10_19_62'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/PIS_1/PIS_1.srcs/sources_1/ip/ram_10_19_62/ram_10_19_62.xci
# IP: The module: 'ram_10_19_62' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/PIS_1/PIS_1.gen/sources_1/ip/ram_10_19_62/ram_10_19_62_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_10_19_62'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
